### ISSUE TITLE
[bug]設定画面から位置情報のパーミッション変更時のクラッシュ不具合

### ISSUE THREAD

**Issue by Yuritani2000** [hakodatemapp/Android_since_2019#18]
**バグの概要**
>症状・再現方法
１．位置情報の権限を与えない状態で地図を表示する。
２．表示設定画面を開き、海抜スイッチをタップ。ダイアログでは「はい」をタップ
３．アプリ設定画面から[権限]→[位置情報]を開く。
４．スイッチをON→OFFにする
５．表示設定画面に戻る。
６．端末の戻るキーかアプリ上の戻るボタンで「表示設定を保存」し、地図を再表示。
７．「問題が発生したため、[はこだてMap+]を終了します」というメッセージが表示
８．パーミッション許可のダイアログが2重に表示され、地図が再表示またはタイトル画面が表示

>現段階で分かっていること
・表示設定を開いているとき、端末設定から位置情報のパーミッション設定を「OFFにする」と発生する模様。
・Logcat上に以下のエラーメッセージが表示。
10-28 16:30:42.033 14865-14865/ac.fun.hakodatemapplus E/AndroidRuntime: FATAL EXCEPTION: main
Process: ac.fun.hakodatemapplus, PID: 14865
java.lang.RuntimeException: Unable to resume activity {ac.fun.hakodatemapplus/ac.fun.hakodatemapplus.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1002, result=-1, data=Intent { (has extras) }} to activity {ac.fun.hakodatemapplus/ac.fun.hakodatemapplus.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.replaceAll(java.lang.String, java.lang.String)' on a null object reference
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3160)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3191)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2529)
at android.app.ActivityThread.access$900(ActivityThread.java:154)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:224)
at android.app.ActivityThread.main(ActivityThread.java:5526)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1002, result=-1, data=Intent { (has extras) }} to activity {ac.fun.hakodatemapplus/ac.fun.hakodatemapplus.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.replaceAll(java.lang.String, java.lang.String)' on a null object reference
at android.app.ActivityThread.deliverResults(ActivityThread.java:3798)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3146)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3191) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2529) 
at android.app.ActivityThread.access$900(ActivityThread.java:154) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:224) 
at android.app.ActivityThread.main(ActivityThread.java:5526) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.replaceAll(java.lang.String, java.lang.String)' on a null object reference
at ac.fun.hakodatemapplus.MainActivity.getSPARQLInvoke(MainActivity.java:760)
at ac.fun.hakodatemapplus.MainActivity.mapRepaint(MainActivity.java:427)
at ac.fun.hakodatemapplus.MainActivity.onActivityResult(MainActivity.java:384)
at android.app.Activity.dispatchActivityResult(Activity.java:6462)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3794)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3146) 
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3191) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2529) 
at android.app.ActivityThread.access$900(ActivityThread.java:154) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:224) 
at android.app.ActivityThread.main(ActivityThread.java:5526) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

**テスト条件**
> 完成の定義をかく。どんなテストをクリアすればこのタスクを完了とみなせるのかを書く。前期とは違って実際にコードを書いているので、条件を満たすテストも行う。(できれば…)  

エラーメッセージを表示されず、アプリが落ちないようにする。

**見積もり**
> どのくらいでタスクが終わるかを見積もったものを書く。単位は(m/人 = 1人でやってなん分かかるか) 
 
[180 m/人]  

**その他注意事項**
> 特筆すべきことがあればここに書く  

[developからdevelop/searchブランチを切って作業をします。]  

****タスク作成者への注意事項****
1. タグ管理をしっかりやってほしいです。上のタスクを例にとると："優先度B", "feat(or 機能)", "search(or 検索)", "form(or 入力フォーム)"くらいは最低限つけてほしい。  
2. このカードの存在を忘れないで(T . T)  
    作ったタスクは移動すべきタイミングでカラムを移動し、最後まで見守りましょう。

**Comment by Yuritani2000** [comment]
訂正：その他注意事項について
現在のブランチlocation/permission/sirotoで実装します。

**Comment by Yuritani2000** [comment]
追記：開発中のブランチlocation/permission/siroto上で発生中です。

**Comment by Yuritani2000** [comment]
アプリの設定画面を開いているときに本体設定のパーミッションをOFFにしてマップに戻ると、onCreateから呼びなおしになると同時に、onActivityResultが呼ばれるようになっているようです。
そのonActivityResultからはmapRepaintが呼ばれるのですが、これが呼ばれるタイミングがonMapReadyが呼ばれるタイミングより早いので、結果的にonMapReadyが呼ばれなければnullのままとなっている変数を複数呼び出してしまい、ヌルポ(NullPointerException)を引き起こしているようです。とりあえずonMapReadyが呼ばれたかを検知するboolean変数を作り、それがtrueかfalseかによってmapRepaintを呼ぶかどうかを判定すればアプリが落ちないようにはなります。しかしこの場合設定画面で設定した項目が反映されないこととなるため、さらなる改善が必要です。

**Comment by Yuritani2000** [comment]
パーミッションをOFFに切り替えたときにActivityが自動的にonCreateから読み直しになるシステムになっているとすれば、location/permission/sirotoには大幅な変更が必要になる可能性があります。

**Comment by Yuritani2000** [comment]
https://github.com/hakodatemapp/Android_since_2019/commit/ec7fdffa911df69053c80489ea00c54df8d1d8e8
上記pushで対処しました。問題点がまだ残っているためまだ修正は必要ですが。

**Comment by Yuritani2000** [comment]
#20 でcloseします。
